main = ".open-next/worker.js"
name = "frontend"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }
[env]
NEXT_PUBLIC_NEST_URL="http://localhost:3000/"
TOKEN="5sQPEJspKvBjXK2D2rupmecTR6OxiClD5AqjMwWESKeI0Tw3QOSMHBWsCcMwTC1x"
NODE_ENV="production"
[[kv_namespaces]]
binding = "NEXT_CACHE_WORKERS_KV"
id = "d733d44d173243bbb0847b9fe4bfffc4"